//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class album_or_radioshow
    {
        public int id { get; set; }
        public string cover { get; set; }
        public string header { get; set; }
        public string author { get; set; }
        public string info { get; set; }
        public Nullable<int> tracklist_id { get; set; }
        public Nullable<int> page_name_id { get; set; }
        public string album_type { get; set; }
        public string src { get; set; }
    
        public virtual tracklist tracklist { get; set; }
        public virtual page_name page_name { get; set; }
    }
}
