//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class album_or_radioshow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public album_or_radioshow()
        {
            this.tracklists = new HashSet<tracklist>();
        }
    
        public int id { get; set; }
        public string cover { get; set; }
        public string album_name { get; set; }
        public string author { get; set; }
        public string info { get; set; }
        public Nullable<int> page_name_id { get; set; }
        public string album_type { get; set; }
    
        public virtual page_name page_name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tracklist> tracklists { get; set; }
    }
}
