//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class music
    {
        public int id { get; set; }
        public string music_cover { get; set; }
        public string music_info { get; set; }
        public Nullable<int> music_types_id { get; set; }
        public string music_src { get; set; }
    
        public virtual music_types music_types { get; set; }
    }
}
