//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myevent
    {
        public int id { get; set; }
        public string event_name { get; set; }
        public string event_info { get; set; }
        public string eventdatetime { get; set; }
        public string photo { get; set; }
        public string event_bk_photo { get; set; }
    }
}
