//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tracklist()
        {
            this.album_or_radioshow = new HashSet<album_or_radioshow>();
        }
    
        public int id { get; set; }
        public string music_name { get; set; }
        public string music_time { get; set; }
        public string music_src { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<album_or_radioshow> album_or_radioshow { get; set; }
    }
}
