//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracklist
    {
        public int id { get; set; }
        public string music_name { get; set; }
        public string music_time { get; set; }
        public string music_src { get; set; }
        public Nullable<int> album_or_radishow_id { get; set; }
    
        public virtual album_or_radioshow album_or_radioshow { get; set; }
    }
}
