//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dj_ReedRussel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public int id { get; set; }
        public string cover { get; set; }
        public string link { get; set; }
        public Nullable<int> video_types_id { get; set; }
    
        public virtual video_types video_types { get; set; }
    }
}
